import RootLayoutClient from "@/components/layout2";
import "./globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Milenial Hotel System",
  description: "Generated by B",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
      </body>
    </html>
  );
}
